// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharpBlog.Data;

#nullable disable

namespace SharpBlog.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20250508013423_AddUserEntity")]
    partial class AddUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharpBlog.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("SharpBlog.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Tech writer and blogger",
                            CreatedAt = new DateTime(2025, 5, 8, 1, 34, 22, 717, DateTimeKind.Utc).AddTicks(7740),
                            Email = "alice@example.com",
                            Name = "Alice",
                            PasswordHash = "placeholder",
                            ProfilePictureUrl = "https://example.com/images/alice.jpg",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "DevOps expert",
                            CreatedAt = new DateTime(2025, 5, 8, 1, 34, 22, 717, DateTimeKind.Utc).AddTicks(7745),
                            Email = "bob@example.com",
                            Name = "Bob",
                            PasswordHash = "placeholder",
                            ProfilePictureUrl = "https://example.com/images/bob.jpg",
                            Role = "Author"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Cloud expert",
                            CreatedAt = new DateTime(2025, 5, 8, 1, 34, 22, 717, DateTimeKind.Utc).AddTicks(7747),
                            Email = "john@example.com",
                            Name = "John",
                            PasswordHash = "placeholder",
                            ProfilePictureUrl = "https://example.com/images/john.jpg",
                            Role = "Reader"
                        });
                });

            modelBuilder.Entity("SharpBlog.Models.BlogPost", b =>
                {
                    b.HasOne("SharpBlog.Models.User", "User")
                        .WithMany("BlogPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SharpBlog.Models.User", b =>
                {
                    b.Navigation("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
