@SharpBlog_HostAddress = https://localhost:7030

POST {{SharpBlog_HostAddress}}/api/blogposts
Content-Type: application/json

  {
    "title": "Asynchronous Programming in C#",
    "content": "Using async and await properly can greatly improve app performance...",
    "category": "Concurrency",
    "tags": "async",
    "authorId": 2
  }

###

GET {{SharpBlog_HostAddress}}/api/blogposts?tag=api

###

GET {{SharpBlog_HostAddress}}/api/blogposts/12

###

DELETE {{SharpBlog_HostAddress}}/api/blogposts/12

###

PUT {{SharpBlog_HostAddress}}/api/blogposts/10
Content-Type: application/json

{
    "title": "Asynchronous Programming in C#",
    "content": "Using async and await properly can greatly improve app performance...",
    "category": "Concuuuurrency",
    "tags": "async",
    "authorId": 2
  }

###
